# Generated by Django 5.0.6 on 2024-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicle',
            name='published_on',
            field=models.DateField(),
        ),
    ]
